User can checkout and pay.
juliocj360/Grabazon pull request #8
Opened 2016-12-02 22:10 UTC by juliocj360

User can now view shopping cart, proceed to checkout, and submit order.  #3

2016-12-02 22:34 UTC, thebearingedge requested changes

2016-12-02 22:34 UTC, thebearingedge commented on default.css
> +.detailBox,
`lower-kebab-case` for CSS selectors.

2016-12-02 22:34 UTC, thebearingedge commented on default.js
> +var checkedRadio = document.getElementById('radioButton1');
Use `lower-kebab-case` for CSS selectors.

2016-12-02 22:34 UTC, thebearingedge commented on default.js
> +function bagReview() {
Add the `event` to this function's parameter list.

2016-12-02 22:34 UTC, thebearingedge commented on default.js
> +//    shipRunner(0)
Remove comments before committing.

2016-12-02 22:34 UTC, thebearingedge commented on default.js
> +    if (addressCheckbox.checked) {
Return opportunistically.
```js
if (addressCheckbox.checked) {
  paymentAddressBox.setAttribute('hidden', 'hidden');
} else {
  paymentAddressBox.removeAttribute('hidden');
}

if (!addressCheckbox.checked) {
  return paymentAddressBox.removeAttribute('hidden');
}
paymentAddressBox.setAttribute('hidden', 'hidden');
```

2016-12-02 22:34 UTC, thebearingedge commented on default.js
> +
WS

2016-12-02 22:34 UTC, thebearingedge commented on index.html
>            <div id="qty-total">Total Items: 0</div>
Don't abbreviate unless your life depends on it.

2016-12-05 04:56 UTC, merged

2016-12-07 20:08 UTC, juliocj360 commented
![screen shot 2016-12-07 at 11 13 22 am](https://cloud.githubusercontent.com/assets/23223086/20984609/e8c232e4-bc75-11e6-813a-777f5b2ed1ae.png)